### ISSUE TITLE
Issue when saving a file

### ISSUE THREAD

**Issue by lokmanm** [Stillat/vscode-antlers-language-server#34] opened 2022-06-16 13:09 UTC
Hi @JohnathonKoster!

First of all great extension and a huge timesaver.

Lately I am noticing an issue with the parser whenever I save a file. I haven't found a way to reproduce this though.

```
[Error - 7:27:42 AM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Maximum call stack size exceeded
  Code: -32603 
  ```

**Comment by JohnathonKoster** [comment] 2022-11-22 00:05
Closing this for now as I haven't been able to reproduce this since the ticket was created. Feel free to re-open it if it shows up after the latest release, however :)

**Closed by JohnathonKoster** 2022-11-22 00:05 UTC
Labels: needs more info
