### ISSUE TITLE
Formatting removes critical Antlers Components syntax

### ISSUE THREAD

**Issue by godismyjudge95** [Stillat/vscode-antlers-language-server#82] opened 2024-01-19 21:43 UTC
**Describe the bug**
Formatting the document removes a critical portion of the Antlers Components syntax:
https://statamic.com/addons/stillat/antlers-components

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [ ] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [x] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
prettier-plugin-antlers - 2.0.1

**To Reproduce**
Paste in the template below and format:
```antlers
{{ attributes.class(['border']) }}
```
It will output:
```antlers
{{ class(['border']) }}
```
Which is no longer accomplishes what the original code does.

**Expected behavior**
It formats the code but doesn't remove critical portions of it.

**Comment by JohnathonKoster** [comment] 2024-01-19 22:51
I cannot reproduce this in version `2.0.1` (this issue existed in a previous version, and was resolved with https://github.com/Stillat/vscode-antlers-language-server/commit/c0b2921fda59d5fb455203572e0768f9a6db239d).

Please verify that you are running `2.0.1`, and if so, feel free to update the information with all necessary steps to reproduce.

**Closed by JohnathonKoster** 2024-01-19 22:51 UTC

**Comment by godismyjudge95** [comment] 2024-01-20 00:06
I swear I checked the version before I ran format and submitted this bug report 😂 

It is working for me on 2.0.1
So sorry for the false alarm 😅
