### ISSUE TITLE
Are tag names supposed to be autocompleted?

### ISSUE THREAD

**Issue by diegovogel** [Stillat/vscode-antlers-language-server#70] opened 2023-04-29 20:56 UTC
**Describe the bug**
I don't know how this extension is supposed to work so this may not be a bug. When I start typing a tag name I would expect it to offer autocomplete suggestions and it never does, for tag names specifically. For example if I type in `{{ par` it won't suggest `partial`. But if I type in `{{ partial:` then it lists partials in my project.
It would also be nice if it automatically closed the tag, e.g. added `{{ /partial }}` when I select an autocomplete option.
I tried disabling all other extensions and restarting VC Code but that didn't make a difference.

![image](https://user-images.githubusercontent.com/23545422/235323708-851be2ca-e265-44da-844b-0f273f1a7abe.png)

**Impacted Products**
Which Antlers Toolbox products does this bug apply to?

- [X] Antlers Toolbox for VS Code
- [ ] Formatter CLI
- [ ] Antlers Prettier Plugin
- [ ] Antlers Syntax Highlighting (external systems - not VS Code)

**Versions and Other Plugins/Extensions**
v2.6.0

**Comment by JohnathonKoster** [comment] 2023-04-29 21:02
At the start of a tag you can force the completions to appear by hitting the completion trigger (on Windows it is Ctrl + Space by default) and begin typing the tag names (will look into improving the some triggers) and begin typing:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/5232890/235324097-5690d355-bc84-4a27-9671-4781ccabe8dd.png">

Not all instances of the partial tag will always be closed, and there is no reliable way to do that without being frustrating for most users.

**Comment by diegovogel** [comment] 2023-05-01 15:20
Thanks for the quick reply. I don't think I explained very well. I am getting suggestions, the problem is they don't include any Antlers tags. This happens whether I manually trigger it or it triggers automatically when I'm typing.

![Screen Cast 2023-05-01 at 11 11 41 AM](https://user-images.githubusercontent.com/23545422/235475400-11684a7c-f044-4f81-a022-905b9a137cc8.gif)

![Screen Cast 2023-05-01 at 11 14 26 AM](https://user-images.githubusercontent.com/23545422/235475540-36bb493f-da02-4873-be05-97d1a0bc1366.gif)

Also, if I understood that last part correctly then it should automatically close some tags, just not the `partial` tag. Is that right? It's not closing any tags for me, but I guess that's because the autocomplete isn't working.

**Comment by JohnathonKoster** [comment] 2023-05-01 15:29
The extension will not auto-close any tags, by design.

I am not able to replicate the auto-complete behavior. If you trigger the manual completions trigger in an empty `{{ }}` does it display a list for you? If not, could you include your emmet/etc. configuration?

Thanks!

**Comment by JohnathonKoster** [comment] 2023-10-28 15:18
Closing issue as it hasn't been reproduced or seen activity in a while.

**Closed by JohnathonKoster** 2023-10-28 15:18 UTC
Labels: cannot reproduce, needs more info

**Comment by montemartin** [comment] 2024-08-26 19:51
@JohnathonKoster I've had this same issue frequently, but I've never been able to figure out any logic to when it fails to work. TBH I think VSCode just hates me because it only fails when I'm actually writing templates. Every time I try to debug it works fine. 🤷
